-- MySQL Script generated by MySQL Workbench
-- 02/25/19 08:31:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema midterm_mvc_exam
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `midterm_mvc_exam` ;

-- -----------------------------------------------------
-- Schema midterm_mvc_exam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `midterm_mvc_exam` DEFAULT CHARACTER SET utf8mb4 ;
USE `midterm_mvc_exam` ;

-- -----------------------------------------------------
-- Table `midterm_mvc_exam`.`tblStudent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midterm_mvc_exam`.`tblStudent` ;

CREATE TABLE IF NOT EXISTS `midterm_mvc_exam`.`tblStudent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `province` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

--
-- Dumping data for table `tblstudent`
--

INSERT INTO `tblstudent` (`id`, `firstname`, `lastname`, `gender`, `phone`, `email`, `province`) VALUES
(1, 'Chendar', 'Hor', 'M', '012345456', 'chendar@gmail.com', 'Pursat'),
(2, 'Sinat', 'Neam', 'F', '012345789', 'sinat@gmail.com', 'Pursat'),
(3, 'Kay', 'Roeuy', 'F', '012345678', 'kay.roeuy@gmail.com', 'Siemreap'),
(4, 'Sreynech', 'chhem', 'F', '096785426', 'sreynech.chhem@gmail.com', 'Banteay Mean Chey');

--
-- Indexes for dumped tables
--


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
